arg_rules:
	latexmk -pdf ./arg_rules.tex

show: arg_rules
	xdg-open ./arg_rules.pdf

clean:
	rm ./arg_rules.pdf;
	rm ./arg_rules.aux;
	rm ./arg_rules.fdb_latexmk;
	rm ./arg_rules.fls;
	rm ./arg_rules.log;
